name: Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.*'
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: make test

    - name: Build all versions
      run: make release
      if: startsWith(github.ref, 'refs/tags/')

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./bin/gocan-linux-amd64
          ./bin/gocan-darwin-amd64